-- AlterTable: generation lineage and versioned content
ALTER TABLE "learning_artifact"
ADD COLUMN "contentVersion" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "attemptCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "cancelledAt" TIMESTAMP(3);

-- Existing rows were generated by a single, untracked attempt.
UPDATE "learning_artifact"
SET "attemptCount" = 1
WHERE "status" <> 'PENDING';

-- AlterEnum: new Studio output types.
-- Added last because a value added in this transaction cannot be used in it.
ALTER TYPE "ArtifactType" ADD VALUE IF NOT EXISTS 'STUDY_GUIDE';
ALTER TYPE "ArtifactType" ADD VALUE IF NOT EXISTS 'FAQ';
ALTER TYPE "ArtifactType" ADD VALUE IF NOT EXISTS 'TIMELINE';
ALTER TYPE "ArtifactType" ADD VALUE IF NOT EXISTS 'BRIEFING';

-- AlterEnum: cancellation is a terminal state distinct from failure
ALTER TYPE "ArtifactStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
